version: '3'
services:
  jenkins_ansible:
    container_name: jenkins_ansible
    image: jenkins_ansible
    build:
      context: jenkins_ansible
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_ansible/config:/var/jenkins_home/ansible
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: remote_host
    build: 
      context: centos7
    volumes:
      - ./centos7/scripts/:/var/run/db/
    networks:
      - net
    env_file:
      - config/.env
  db_host:
    container_name: db
    image: mysql:5.7
    env_file:
      - config/db-variables.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/config:/var/tmp
    networks:
      - net
networks:
  net:
